### ISSUE TITLE
it's seems cannot use the backgroundImage in the stss

### ISSUE THREAD

**Issue by winsonet** [RonaldTreur/STSS#19]
when I try to set the backgroundImage, it's always failed :(
For example, I set the bg image like below:
~~~
#Wrapper {
	layout: 'composite';
	backgroundImage: 'Default.png';
}
~~~
there are following errors:
~~~
[ERROR] :  Error processing style "..../app/styles/home.tss"
[ERROR] :  Expected "Alloy", "L", "Ti", "Titanium", "WPATH", "[", "false", "null", "true", "undefined", "{", comment, end of line, number, string or whitespace but "D" found.
[ERROR] :
[ERROR] :  - line:    4
[ERROR] :  - column:  19
[ERROR] :  - offset:  56
[ERROR] :  Alloy compiler failed
~~~

when I set the bg image like below:
~~~
#Wrapper {
	layout: 'composite';
	backgroundImage: '/images/Default.png';
}
~~~

there is no error, but the result is:
~~~
#Wrapper {
	layout: 'composite';
	backgroundImage: "/images/\"Default.png\""
}
~~~
and this path will cannot work, I don't know why it will auto add the double quote when there is a '/' in the path :(

**Comment by RonaldTreur** [comment]
It's been awhile, but a fix is inbound.

Aside from `backgroundImage` (and the Android variants that are part of`View`), if anyone knows of other properties that can be assigned a file, please let me know!
