### ISSUE TITLE
Alpha transparent background colors in Android

### ISSUE THREAD

**Issue by jvandijk** [RonaldTreur/STSS#21]
I ran into another issue when trying to create logic like issue #20, but now specifically for Android.

For Android the RGBA logic works differently then iOS. In iOS the last parameter should have a value between 0 and 1, Android thought requires a value between 0 and 225.

Trying to create this TSS output:
```
".myview":{
    backgroundColor : rgba(255,0,0,127)
}
```
is something that does not work in STSS, because it complains about the fact that the alpha value should be between 0 and 1.

Any idea if this could be solved?

**Comment by vdesdoigts** [comment]
You can use `backgroundColor: "#99000000"` instead of `backgroundColor: rgba(0,0,0, 0.6)` for example.

**Comment by RonaldTreur** [comment]
This is a tough problem.. Using queries seems to be the most straightforward solution, similar to how you would resolve this in pure TSS. Or the hex-variant as @vdesdoigts mentions (and I fixed just now).

I'm not sure what other options there are. We could create iOS and Android versions of all selectors that contain alpha-colors, but if you're only creating an iOS app (for example) that might be annoying. Suggestions are welcome however!

I'm closing this for now, but if someone comes up with a viable solution I'll reopen it.
